### ISSUE TITLE
Question: ClusterAutoscaler & Managed Node Groups

### ISSUE THREAD

**Issue by mbiokyle29** [aws-quickstart/quickstart-amazon-eks#147]
I have a question about using the ClusterAutoscaler along with AWS Managed Node Groups. If this is not the appropriate venue for questions, my apologizes for posting here. If it is okay then, my question is why does the template enforce that you cannot use the cluster auto scaler with AWS managed node groups:

```yaml
# https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/amazon-eks-master.template.yaml#L433

  ClusterAutoScalerVerification:
    RuleCondition: !Equals [ !Ref 'ManagedNodeGroup', 'yes' ]
    Assertions:
      - AssertDescription: To use Cluster AutoScaler you should not use Managed Node Groups
        Assert: !Contains
          - - 'Disabled'
          - !Ref 'ClusterAutoScaler'

```

Based on this userguide: https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html
It seems that this configuration is supported. I was just wondering if this is a hard limitation on the platform or if this a limitation of the this template stack. Either way, I appreciate all the hard work on this stack and any guidance on this issue.
