### ISSUE TITLE
Helm error

### ISSUE THREAD

**Issue by chitender** [aws-quickstart/quickstart-amazon-eks#187]
Hi,

we are trying to deploy the Helm chart by using Helm lambda. below is our AWS CF template:
```
AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys the prometheus helm chart into an existing kubernetes cluster (qs-1qde66ffn)"
Parameters:
  HelmLambdaArn:
    Type: String
    Default: "arn:aws:lambda:ap-south-1:XXXXXXXXXXXX:function:v3atlan-EKSFunctionStack-GINPJDY5EXW1-HelmLambda-1AEDP2LG6ABM8"
  KubeConfigPath:
    Type: String
    Default: "s3://v3-XXXXXXX/.kube/config.enc"
  KubeConfigKmsContext:
    Type: String
    Default: "Atlan"
  enableMonitoring:
    Type: String
    Default: "true"
  ReplicaCount:
    Type: String
    Default: "1"
Resources:
  # Install prometheus helm chart
  nginxHelmChart:
    Type: "Custom::Helm"
    Version: "1.0"
    Properties:
      ClusterID: v3atlan
      ServiceToken: !Ref HelmLambdaArn
      KubeConfigPath: !Ref KubeConfigPath
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      RepoUrl: https://kubernetes-charts.storage.googleapis.com/
      Namespace: chitender
      Chart: stable/ingress-nginx
Outputs:
  PrometheusReleaseName:
    Value: !Ref nginxHelmChart
```

when executing the CF template we are getting error:
```
Failed to create resource. ERROR: (truncated) listening on 127.0.0.1:44134 [main] 2020/09/14 10:36:24 Probes listening on :44135 [main] 2020/09/14 10:36:24 Storage driver is Secret [main] 2020/09/14 10:36:24 Max history per release is 0 Error: This command needs 1 argument: chart name
```

any suggestion or guidance on this will be helpfull.

```
