### ISSUE TITLE
Nodeautoscalinggroup is always None in amazon-eks-cluster-autoscaler.template.yaml

### ISSUE THREAD

**Issue by nandexsp** [aws-quickstart/quickstart-amazon-eks#225]
When the parameter **NodeAutoscalingGroup** enter in the template is always None :/ and the policy Name is always None and if you create two clusters, the second will has an error with that: 

```
ClusterAutoScalerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${NodeAutoScalingGroup}'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:DescribeAutoScalingInstances
              - autoscaling:DescribeLaunchConfigurations
              - autoscaling:DescribeTags
            Resource: "*"
          - Effect: Allow
            Action:
              - autoscaling:SetDesiredCapacity
              - autoscaling:TerminateInstanceInAutoScalingGroup
            Resource: !Sub "arn:${AWS::Partition}:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:*:autoScalingGroupName/${NodeAutoScalingGroup}"
      Roles:
        - !Sub ['${Prefix}-ManagedNodeInstance', {Prefix: !FindInMap [Config, Prefix, Value]}]
        - !Sub ['${Prefix}-UnManagedNodeInstance', {Prefix: !FindInMap [Config, Prefix, Value]}]
```

**Suggested Solution:**

Use for PolicyName the EksClusterName

**PolicyName: !Ref EksClusterName**
