### ISSUE TITLE
Create Failed - ClusterAutoScalerStack

### ISSUE THREAD

**Issue by phenri00** [aws-quickstart/quickstart-amazon-eks#247]
2020-11-16 14:34:03 UTC+0100	Amazon-EKS-EKSStack-GJ7UJIBPW9RJ-ClusterAutoScalerStack-Y15NSEH87HT9	CREATE_FAILED	The following resource(s) failed to create: [AutoScalerHelmChart].
2020-11-16 14:34:02 UTC+0100	AutoScalerHelmChart	CREATE_FAILED	[errorString] Error: At Helm Upgrade - failed to download "stable/cluster-autoscaler" (hint: running `helm repo update` may help)

Guessing helm repo location?

https://helm.sh/blog/new-location-stable-incubator-charts/

**Comment by phenri00** [comment]
Should update to latest commit on following submodule: 

quickstart-helm-resource-provider

**Comment by cwardcode** [comment]
Came here to report this as well

@phenri00 Any idea when the latest is going to be published? This is currently blocking me from deploying a new cluster

**Comment by phenri00** [comment]
It's fixed in the main repo(but there is no new release).

Workaround is to disable the autoscaler during bootstrapping, and then manually install autoscaler with helm when the cluster is up.

**Comment by cwardcode** [comment]
I ended up taking the "clone & build the repo and then copy the zip" route.. however, I'm still getting the same error.

**Comment by commandosss** [comment]
EFSProvisioner Create Failed
[errorString] Error: At Helm Upgrade - failed to download "stable/efs-provisioner" (hint: running `helm repo update` may help)

**Comment by kcheemz** [comment]
> It's fixed in the main repo(but there is no new release).
> 
> Workaround is to disable the autoscaler during bootstrapping, and then manually install autoscaler with helm when the cluster is up.
> 
> Edit: You could also clone & build the repo and then copy the zip of quickstart-helm-resource-provider into you own repo.

Also having issues, could you elaborate more on your solution? Not sure what's meant by 'add-on' templates. Thanks in advance!

**Comment by cwardcode** [comment]
@kcheemz I modified the templates located in the /templates directory, such as the [efs template](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-efs.template.yaml). I updated the [`AWSQS::Kubernetes:Helm`](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-efs.template.yaml#L84) resource to include a `Repository` property and pointed that at the new stable location, so that the resource now looks like this:

```
    Type: 'AWSQS::Kubernetes::Helm'
    Properties:
      ClusterID: !Ref ClusterName
      Namespace: efs-provisioner
      Chart: stable/efs-provisioner
      Repository: 'https://charts.helm.sh/stable'
      Values:
        efsProvisioner.efsFileSystemId: !Ref EFSFileSystem
        efsProvisioner.awsRegion: !Ref 'AWS::Region'
        efsProvisioner.provisionerName: aws-quickstart/aws-efs
```
