### ISSUE TITLE
Upgrade EKS stack 

### ISSUE THREAD

**Issue by cf-mark-de-boer** [aws-quickstart/quickstart-amazon-eks#284]
Hi,
I am trying to upgrade a EKS stack made in July 2020. I am seeing a lot of differences. I have tried creating the shared resources stacks and custom configuration stack. I am getting the following error when trying to create a changeset for the nest stack: "Update of resource type is not permitted. The new template modifies resource type of the following resources: [CleanupLambdas]"

This is the custom resource in the EKS base stack:

Old version:
```
  CleanupLambdas:
    Condition: CreateLambdaZipsBucket
    Type: Custom::CleanupLambdas
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt 'FunctionStack.Outputs.CleanupLambdasLambdaArn'
      SecurityGroupId: !Ref ControlPlaneSecurityGroup
```
New version:
```
  CleanupLambdas:
    Type: Custom::LambdaCleanup
    DependsOn: CleanupControlPlaneSecurityGroupDependencies
    Properties:
      ServiceToken: !Sub ['arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${Prefix}-CleanupLambdas', {Prefix: !FindInMap [Config, Prefix, Value]}]
      SecurityGroupId: !GetAtt ControlPlaneSecurityGroup.GroupId
```
Any hints on how to approach this upgrade? 

Regards,
Mark
