### ISSUE TITLE
Error when passing YAML Manifest to Manifest field in "AWSQS::Kubernetes::Resource"

### ISSUE THREAD

**Issue by nitnagpal** [aws-quickstart/quickstart-amazon-eks#296]
`Properties validation failed for resource KubeManifestExample with message: #/Manifest: expected type: String, found: JSONObject`

The Manifest property in Custom Resource "AWSQS::Kubernetes::Resource" is set to be a string. It gives the above error during cloudformation stack creation and works if Kubernetes Manifest is passed as string with json manifest

https://github.com/aws-quickstart/quickstart-kubernetes-resource-provider/blob/2775f1c988e495970f4d8553224e3eed3d8016f8/apply/awsqs-kubernetes-resource.json#L14-L17

Cloudformation failed for the below example
```
  KubeManifestExample:
    Type: "AWSQS::Kubernetes::Resource"
    Metadata: { cfn-lint: { config: { ignore_checks: [E3002] } } }
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: kube-system
      # Kubernetes manifest
      Manifest:
        apiVersion: v1
        kind: ConfigMap
        # metadata:
          # If name is not specified it will be automatically generated,
          # and can be retrieved with !GetAtt LogicalID.name
          #
          # name: test
          #
        data:
          # examples of consuming outputs of the HelmExample resource below's output. Creates an implicit dependency, so
          # this resource will only launch once the HelmExample resource has completed successfully
          GrafanaId: !Ref HelmExample
```

Below is with json manifest which works 
```
  KubeManifestExample:
    Type: "AWSQS::Kubernetes::Resource"
    Metadata: { cfn-lint: { config: { ignore_checks: [E3002] } } }
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: grafana
      # Kubernetes manifest
      Manifest: '{
    "kind": "ConfigMap",
    "apiVersion": "v1",
    "metadata": {
        "name": "my-config",
        "creationTimestamp": null
    },
    "data": {
        "key1": "config"
    }
}'
```
