### ISSUE TITLE
Annotations does not support boolean values but KubeManifest converts string 'true' to boolean

### ISSUE THREAD

**Issue by vissree** [aws-quickstart/quickstart-amazon-eks#304]
Issues
-------
1) The Lambda function backing the Custom::KubeManifest resource converts all string 'true' and 'false' values to boolean true and false. Annotations does not support boolean type in values.
2) The kubectl binary supplied as a layer to the lambda function is of version 1.16 which is silently dropping the annotation when the value is a boolean.

The core issue here is (1) and (2) is masking the error and creating the resource without the annotations causing unexpected results.

Steps to reproduce
--------------------

1) Create a Service resource using the below template
``` yaml
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  KubeClusterName:
    Type: String
Resources:
  SampleService:
      Type: "Custom::KubeManifest"
      Version: '1.0'
      Properties:
        ServiceToken: !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:EKS-QuickStart-KubeManifest-${KubeClusterName}"
        ClusterName: !Ref KubeClusterName
        Manifest:
          apiVersion: v1
          kind: Service
          metadata:
            name: sample-service
            namespace: default
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-internal: "true"
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
              service.beta.kubernetes.io/aws-oad-balancer-type: nlb    
          spec:
            selector:
              app: sample-app
            ports:
            - protocol: TCP
              port: 1433
            type: LoadBalancer
            loadBalancerSourceRanges: 
            - "10.0.0.0/8"
```

The annotations are dropped in the create API call and the Service is created with a Classic Loadbalancer. Following is the Request object from API audit log. We can see that annotations: {} is empty in the last applied configuration and the metadata does not include the load-balancer specific annotations we added in the resource properties.
``` json
    "requestObject": {
        "kind": "Service",
        "apiVersion": "v1",
        "metadata": {
            "name": "sample-service",
            "namespace": "default",
            "creationTimestamp": null,
            "annotations": {
                "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"name\":\"sample-service\",\"namespace\":\"default\"},\"spec\":{\"loadBalancerSourceRanges\":[\"10.0.0.0/8\"],\"ports\":[{\"port\":1433,\"protocol\":\"TCP\"}],\"selector\":{\"app\":\"sample-app\"},\"type\":\"LoadBalancer\"}}\n"
            }
        },
        "spec": {
            "ports": [
                {
                    "protocol": "TCP",
                    "port": 1433,
                    "targetPort": 1433
                }
            ],
            "selector": {
                "app": "sample-app"
            },
            "type": "LoadBalancer",
            "sessionAffinity": "None",
            "loadBalancerSourceRanges": [
                "10.0.0.0/8"
            ],
            "externalTrafficPolicy": "Cluster"
        },
        "status": {
            "loadBalancer": {}
        }
    },
```

The parsed manifest json object from the the KubeManifest lambda function is available in CloudWatch logs, where we can see that the annotation's value is converted to boolean true.
``` json
"message": "Applying manifest: {\"metadata\": {\"name\": \"sample-service\", \"namespace\": \"default\", \"annotations\": {\"service.beta.kubernetes.io/aws-oad-balancer-type\": \"nlb\", \"service.beta.kubernetes.io/aws-load-balancer-internal\": true, \"service.beta.kubernetes.io/aws-load-balancer-backend-protocol\": \"tcp\"}}, \"apiVersion\": \"v1\", \"kind\": \"Service\", \"spec\": {\"loadBalancerSourceRanges\": [\"10.0.0.0/8\"], \"selector\": {\"app\": \"sample-app\"}, \"ports\": [{\"protocol\": \"TCP\", \"port\": 1433}], \"type\": \"LoadBalancer\"}}"
```

If we use the same manifest object and run the `kubectl create` command (using kubectl version 1.18 in this case) it fails during decode.
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-eks-7c9bda", GitCommit:"7c9bda52c425d0d56d7b93f1377a826b4132c05c", GitTreeSta
te:"clean", BuildDate:"2020-08-28T23:07:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeSta
te:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl create --save-config -o json -f service.json
error: unable to decode "service.json": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|ternal": true, "exte|..., bigger context ...|.beta.kubernetes.io/aws-load-balancer-internal": true, "external-dns.alpha.kubernetes.io/hostname": |...
```

However, running the same using the kubectl binary, shipped along with the Lambda function as a layer, creates the resource by silently dropping the annotations.
```
$ ./kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeSta
te:"clean", BuildDate:"2020-03-27T22:40:13Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeSta
te:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

 ./kubectl create --save-config -o json -f service.json  
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"name\"
:\"sample-service-2\",\"namespace\":\"default\"},\"spec\":{\"loadBalancerSourceRanges\":[\"10.0.0.0/8\"],\"ports\":[{\"port\":1433,\"protocol\":\"TCP\
"}],\"selector\":{\"app\":\"sample-app\"},\"type\":\"LoadBalancer\"}}\n"
        },
        "creationTimestamp": "2021-03-26T06:10:22Z",
        "managedFields": [
            {
                "apiVersion": "v1",
                "fieldsType": "FieldsV1",
                "fieldsV1": {
                    "f:metadata": {
                        "f:annotations": {
                            ".": {},
                            "f:kubectl.kubernetes.io/last-applied-configuration": {}
                        }
                    },
                    "f:spec": {
                        "f:externalTrafficPolicy": {},
                        "f:loadBalancerSourceRanges": {},
                        "f:ports": {
                            ".": {},
                            "k:{\"port\":1433,\"protocol\":\"TCP\"}": {
                                ".": {},
                                "f:port": {},
                                "f:protocol": {},
                                "f:targetPort": {}
                            }
                        },
                        "f:selector": {
                            ".": {},
                            "f:app": {}
                        },
                        "f:sessionAffinity": {},
                        "f:type": {}
                    }
                },
                "manager": "kubectl",
                "operation": "Update",
                "time": "2021-03-26T06:10:22Z"
            }
        ],
        "name": "sample-service-2",
        "namespace": "default",
        "resourceVersion": "53686",
        "selfLink": "/api/v1/namespaces/default/services/sample-service-2",
        "uid": "cbe05d90-60ea-4f5e-97f8-6aeff9a23ff3"
    },
    "spec": {
        "clusterIP": "172.20.77.222",
        "externalTrafficPolicy": "Cluster",
        "loadBalancerSourceRanges": [
            "10.0.0.0/8"
        ],
        "ports": [
            {
                "nodePort": 31298,
                "port": 1433,
                "protocol": "TCP",
                "targetPort": 1433
            }
        ],
        "selector": {
            "app": "sample-app"
        },
        "sessionAffinity": "None",
        "type": "LoadBalancer"
    },
    "status": {
        "loadBalancer": {}
    }
}
```

Workaround
-------------

A possible workaround is to not run the set_type() function if the path is a sub-path of metadata -> annotations. I have created a PR with this workaround in place if that helps.

**Comment by jaymccon** [comment]
thanks for the thorough write up @vissree . This issue stems from CloudFormation converting the type of every property to a string before passing it to the custom resource lambda, so if the custom resource is invoked using a json/yaml object for the `Manifest` property we try to guess which strings were originally `bool`/`int`/etc. This is suboptimal for cases like this where k8s is expecting a string representation of another type.

It is for this reason that the resource type [`AWSQS::Kubernetes::Resource`](https://github.com/aws-quickstart/quickstart-kubernetes-resource-provider/tree/main/apply) that supersedes the `Custom::KubeManifest` only allows providing the manifest as a string.

For a workaround that doesn't require any code changes, you should be able to provide your manifest as a string, which stops cfn from re-casting the sub-element values. For example:
```yaml
        Manifest:
          apiVersion: v1
          kind: Service
          metadata:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```
would become:
```yaml
        Manifest: |
          apiVersion: v1
          kind: Service
          metadata:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```
Also note that `Custom::KubeManifest` is deprecated and will be removed from the next majow version release of the Quick Start.
