### ISSUE TITLE
Can't get pod logs on bastion host.

### ISSUE THREAD

**Issue by jaggerwang** [aws-quickstart/quickstart-amazon-eks#388]
After successfully created an EKS cluster by this quickstart, I can exetute the following kubectl commands on bastion host.

![image](https://user-images.githubusercontent.com/1255011/145191830-eda00847-4273-4ac3-abe1-c1ecb99695e7.png)

But when I exetute kubectl logs I got error "Error from server (InternalError): Internal error occurred: Authorization error (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)".

![image](https://user-images.githubusercontent.com/1255011/145192041-4e9eb013-4e5f-4e98-8b3e-c23ee087f2ef.png)

**Comment by jaggerwang** [comment]
I already tried to create the following ClusterRoleBinding as this article [kubectl logs -f gets "Authorization error"](https://stackoverflow.com/questions/54572775/kubectl-logs-f-gets-authorization-error) saied, it's the same.

```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubelet-api-admin
subjects:
- kind: User
  name: kube-apiserver-kubelet-client
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: system:kubelet-api-admin
  apiGroup: rbac.authorization.k8s.io
```
