### ISSUE TITLE
how to pass manifest file to Custom::KubeManifest in Cloudformation

### ISSUE THREAD

**Issue by chitender** [aws-quickstart/quickstart-amazon-eks#98]
Hi,

at present we are trying by defining resources for each kubernetes object. like if our deployment need ClusterRole, Service, PVC and Deployment. then we need to define 4 individual resources in Cloudformation template.

is there a way in which we can directly pass our manifest.yaml which has all the objects definition to Custom:KubeManifest?

**Comment by jaymccon** [comment]
In CloudFormation it is concidered best practive to have 1 resource represent exactly one thing. That said you should be able to do it by passing raw yaml as a string literal:

```yaml
  KubeManifestExample:
    Type: "Custom::KubeManifest"
    Properties:
      Manifest: | 
        ---
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: anItem
        ---
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: anotherItem
```
